// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace STP.Repository.Models;

public partial class Deposit
{
    public int Id { get; set; }

    public int? WalletId { get; set; }

    public int UserId { get; set; }

    public decimal? Amount { get; set; }

    public string DepositMethod { get; set; }

    public DateTime? DepositDate { get; set; }

    public int? Status { get; set; }

    public virtual ICollection<Transaction> Transactions { get; set; } = new List<Transaction>();

    public virtual User User { get; set; }

    public virtual Wallet Wallet { get; set; }
}