<<<<<<< Updated upstream
﻿using System;
=======
﻿// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
>>>>>>> Stashed changes
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace STP.Repository.Models;

public partial class ShareTaxiContext : DbContext
{
<<<<<<< Updated upstream
    public ShareTaxiContext()
    {
    }

    public ShareTaxiContext(DbContextOptions<ShareTaxiContext> options)
        : base(options)
    {
    }

=======
    public ShareTaxiContext() { }
    public ShareTaxiContext(DbContextOptions<ShareTaxiContext> options)
        : base(options)
    {
    }

>>>>>>> Stashed changes
    public virtual DbSet<Area> Areas { get; set; }

    public virtual DbSet<Booking> Bookings { get; set; }

    public virtual DbSet<CarTrip> CarTrips { get; set; }

    public virtual DbSet<Deposit> Deposits { get; set; }

    public virtual DbSet<Location> Locations { get; set; }

<<<<<<< Updated upstream
    public virtual DbSet<Pricing> Pricings { get; set; }

=======
>>>>>>> Stashed changes
    public virtual DbSet<Transaction> Transactions { get; set; }

    public virtual DbSet<Trip> Trips { get; set; }

<<<<<<< Updated upstream
=======
    public virtual DbSet<TripType> TripTypes { get; set; }

    public virtual DbSet<TripeTypePricing> TripeTypePricings { get; set; }

>>>>>>> Stashed changes
    public virtual DbSet<User> Users { get; set; }

    public virtual DbSet<Wallet> Wallets { get; set; }

<<<<<<< Updated upstream
    public static string GetConnectionString(string connectionStringName)
    {
        var config = new ConfigurationBuilder()
            .SetBasePath(AppDomain.CurrentDomain.BaseDirectory)
            .AddJsonFile("appsettings.json")
            .Build();

        string connectionString = config.GetConnectionString(connectionStringName);
        return connectionString;
    }
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder.UseSqlServer(GetConnectionString("DefaultConnection"));
    //    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    //#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
    //        => optionsBuilder.UseSqlServer("Data Source=ADMIN-PC\\MSSQLSERVER1;Initial Catalog=Share_Taxi;Persist Security Info=True;User ID=sa;Password=12345;Encrypt=False");

=======
>>>>>>> Stashed changes
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Area>(entity =>
        {
<<<<<<< Updated upstream
            entity.HasKey(e => e.Id).HasName("PK__Area__3214EC07AAF2535E");

            entity.ToTable("Area");

            entity.Property(e => e.Id).ValueGeneratedNever();
=======
            entity.HasKey(e => e.Id).HasName("PK__Area__3214EC07CAE89BF7");

            entity.ToTable("Area");

>>>>>>> Stashed changes
            entity.Property(e => e.Description).HasMaxLength(255);
            entity.Property(e => e.Name).HasMaxLength(255);
        });

        modelBuilder.Entity<Booking>(entity =>
        {
<<<<<<< Updated upstream
            entity.HasKey(e => e.Id).HasName("PK__Booking__3214EC0719D2871E");

            entity.ToTable("Booking");

            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.HasOne(d => d.Trip).WithMany(p => p.Bookings)
                .HasForeignKey(d => d.TripId)
                .HasConstraintName("FK__Booking__TripId__35BCFE0A");

            entity.HasOne(d => d.User).WithMany(p => p.Bookings)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK__Booking__UserId__36B12243");
=======
            entity.HasKey(e => e.Id).HasName("PK__Booking__3214EC0763EB8E6B");

            entity.ToTable("Booking");

            entity.HasOne(d => d.Trip).WithMany(p => p.Bookings)
                .HasForeignKey(d => d.TripId)
                .HasConstraintName("FK__Booking__TripId__37A5467C");

            entity.HasOne(d => d.User).WithMany(p => p.Bookings)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK__Booking__UserId__38996AB5");
>>>>>>> Stashed changes
        });

        modelBuilder.Entity<CarTrip>(entity =>
        {
<<<<<<< Updated upstream
            entity.HasKey(e => e.Id).HasName("PK__CarTrip__3214EC07E139768C");

            entity.ToTable("CarTrip");

            entity.Property(e => e.Id).ValueGeneratedNever();
=======
            entity.HasKey(e => e.Id).HasName("PK__CarTrip__3214EC0793EC464B");

            entity.ToTable("CarTrip");

>>>>>>> Stashed changes
            entity.Property(e => e.DriverName).HasMaxLength(255);
            entity.Property(e => e.DriverPhone).HasMaxLength(255);
            entity.Property(e => e.PlateNumber).HasMaxLength(255);

            entity.HasOne(d => d.Trip).WithMany(p => p.CarTrips)
                .HasForeignKey(d => d.TripId)
<<<<<<< Updated upstream
                .HasConstraintName("FK__CarTrip__TripId__37A5467C");
=======
                .HasConstraintName("FK__CarTrip__TripId__398D8EEE");
>>>>>>> Stashed changes
        });

        modelBuilder.Entity<Deposit>(entity =>
        {
<<<<<<< Updated upstream
            entity.HasKey(e => e.Id).HasName("PK__Deposit__3214EC07403D6C67");

            entity.ToTable("Deposit");

            entity.Property(e => e.Id).ValueGeneratedNever();
=======
            entity.HasKey(e => e.Id).HasName("PK__Deposit__3214EC0717761347");

            entity.ToTable("Deposit");

>>>>>>> Stashed changes
            entity.Property(e => e.Amount).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.DepositDate).HasColumnType("datetime");
            entity.Property(e => e.DepositMethod).HasMaxLength(255);

<<<<<<< Updated upstream
            entity.HasOne(d => d.Transaction).WithMany(p => p.Deposits)
                .HasForeignKey(d => d.TransactionId)
                .HasConstraintName("FK__Deposit__Transac__38996AB5");

            entity.HasOne(d => d.Wallet).WithMany(p => p.Deposits)
                .HasForeignKey(d => d.WalletId)
                .HasConstraintName("FK__Deposit__WalletI__398D8EEE");
=======
            entity.HasOne(d => d.User).WithMany(p => p.Deposits)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Deposit__UserId__3A81B327");

            entity.HasOne(d => d.Wallet).WithMany(p => p.Deposits)
                .HasForeignKey(d => d.WalletId)
                .HasConstraintName("FK__Deposit__WalletI__3B75D760");
>>>>>>> Stashed changes
        });

        modelBuilder.Entity<Location>(entity =>
        {
<<<<<<< Updated upstream
            entity.HasKey(e => e.Id).HasName("PK__Location__3214EC270A8845DF");

            entity.ToTable("Location");

            entity.Property(e => e.Id)
                .ValueGeneratedNever()
                .HasColumnName("ID");
=======
            entity.HasKey(e => e.Id).HasName("PK__Location__3214EC0757062A9D");

            entity.ToTable("Location");

>>>>>>> Stashed changes
            entity.Property(e => e.Lat).HasColumnType("decimal(10, 8)");
            entity.Property(e => e.Lon).HasColumnType("decimal(11, 8)");
            entity.Property(e => e.Name).HasMaxLength(255);

            entity.HasOne(d => d.Area).WithMany(p => p.Locations)
                .HasForeignKey(d => d.AreaId)
<<<<<<< Updated upstream
                .HasConstraintName("FK__Location__AreaId__3A81B327");
        });

        modelBuilder.Entity<Pricing>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Pricing__3214EC071C6F3D43");

            entity.ToTable("Pricing");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Currency).HasMaxLength(255);
            entity.Property(e => e.Price).HasColumnType("decimal(10, 2)");

            entity.HasOne(d => d.DropOffLocation).WithMany(p => p.PricingDropOffLocations)
                .HasForeignKey(d => d.DropOffLocationId)
                .HasConstraintName("FK__Pricing__DropOff__3B75D760");

            entity.HasOne(d => d.PickUpLocation).WithMany(p => p.PricingPickUpLocations)
                .HasForeignKey(d => d.PickUpLocationId)
                .HasConstraintName("FK__Pricing__PickUpL__3C69FB99");
=======
                .HasConstraintName("FK__Location__AreaId__3C69FB99");
>>>>>>> Stashed changes
        });

        modelBuilder.Entity<Transaction>(entity =>
        {
<<<<<<< Updated upstream
            entity.HasKey(e => e.Id).HasName("PK__Transact__3214EC077164203C");

            entity.ToTable("Transaction");

            entity.Property(e => e.Id).ValueGeneratedNever();
=======
            entity.HasKey(e => e.Id).HasName("PK__Transact__3214EC0753E4BED1");

            entity.ToTable("Transaction");

>>>>>>> Stashed changes
            entity.Property(e => e.Amount).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.CreatedAt).HasColumnType("datetime");
            entity.Property(e => e.ReferenceId).HasMaxLength(255);
            entity.Property(e => e.TransactionType).HasMaxLength(255);

<<<<<<< Updated upstream
            entity.HasOne(d => d.Wallet).WithMany(p => p.Transactions)
                .HasForeignKey(d => d.WalletId)
                .HasConstraintName("FK__Transacti__Walle__3D5E1FD2");
=======
            entity.HasOne(d => d.Deposit).WithMany(p => p.Transactions)
                .HasForeignKey(d => d.DepositId)
                .HasConstraintName("FK_Transaction_Deposit");

            entity.HasOne(d => d.Wallet).WithMany(p => p.Transactions)
                .HasForeignKey(d => d.WalletId)
                .HasConstraintName("FK__Transacti__Walle__3E52440B");
>>>>>>> Stashed changes
        });

        modelBuilder.Entity<Trip>(entity =>
        {
<<<<<<< Updated upstream
            entity.HasKey(e => e.Id).HasName("PK__Trip__3214EC07C4EB0600");

            entity.ToTable("Trip");

            entity.Property(e => e.Id).ValueGeneratedNever();
=======
            entity.HasKey(e => e.Id).HasName("PK__Trip__3214EC07EBFD2347");

            entity.ToTable("Trip");

>>>>>>> Stashed changes
            entity.Property(e => e.BookingDate).HasColumnType("datetime");
            entity.Property(e => e.DropOffLocationId).HasColumnName("dropOffLocationId");
            entity.Property(e => e.PickUpLocationId).HasColumnName("pickUpLocationId");
            entity.Property(e => e.UnitPrice).HasColumnType("decimal(10, 2)");

            entity.HasOne(d => d.DropOffLocation).WithMany(p => p.TripDropOffLocations)
                .HasForeignKey(d => d.DropOffLocationId)
<<<<<<< Updated upstream
                .HasConstraintName("FK__Trip__dropOffLoc__3E52440B");

            entity.HasOne(d => d.PickUpLocation).WithMany(p => p.TripPickUpLocations)
                .HasForeignKey(d => d.PickUpLocationId)
                .HasConstraintName("FK__Trip__pickUpLoca__3F466844");

            entity.HasOne(d => d.Pricing).WithMany(p => p.Trips)
                .HasForeignKey(d => d.PricingId)
                .HasConstraintName("FK__Trip__PricingId__403A8C7D");

            entity.HasOne(d => d.ToArea).WithMany(p => p.Trips)
                .HasForeignKey(d => d.ToAreaId)
                .HasConstraintName("FK__Trip__ToAreaId__412EB0B6");
=======
                .HasConstraintName("FK__Trip__dropOffLoc__3F466844");

            entity.HasOne(d => d.PickUpLocation).WithMany(p => p.TripPickUpLocations)
                .HasForeignKey(d => d.PickUpLocationId)
                .HasConstraintName("FK__Trip__pickUpLoca__403A8C7D");

            entity.HasOne(d => d.TripType).WithMany(p => p.Trips)
                .HasForeignKey(d => d.TripTypeId)
                .HasConstraintName("FK_Trip_TripType");
        });

        modelBuilder.Entity<TripType>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__TripType__3214EC070242C8F9");

            entity.ToTable("TripType");

            entity.Property(e => e.BasicePrice).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(255);
        });

        modelBuilder.Entity<TripeTypePricing>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__TripeTyp__3214EC0705F606D8");

            entity.ToTable("TripeTypePricing");

            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.PricePerPerson).HasColumnType("decimal(10, 2)");

            entity.HasOne(d => d.TripTypeNavigation).WithMany(p => p.TripeTypePricings)
                .HasForeignKey(d => d.TripType)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_TripTypePricing_TripType");
>>>>>>> Stashed changes
        });

        modelBuilder.Entity<User>(entity =>
        {
<<<<<<< Updated upstream
            entity.HasKey(e => e.Id).HasName("PK__User__3214EC075541214B");

            entity.ToTable("User");

            entity.Property(e => e.Id).ValueGeneratedNever();
=======
            entity.HasKey(e => e.Id).HasName("PK__User__3214EC07FF3406D1");

            entity.ToTable("User");

>>>>>>> Stashed changes
            entity.Property(e => e.CreatedAt).HasColumnType("datetime");
            entity.Property(e => e.Email).HasMaxLength(255);
            entity.Property(e => e.Name).HasMaxLength(255);
            entity.Property(e => e.Password).HasMaxLength(255);
            entity.Property(e => e.PhoneNumber).HasMaxLength(255);
            entity.Property(e => e.Role).HasMaxLength(255);
        });

        modelBuilder.Entity<Wallet>(entity =>
        {
<<<<<<< Updated upstream
            entity.HasKey(e => e.Id).HasName("PK__Wallet__3214EC072A2A5CD3");

            entity.ToTable("Wallet");

            entity.Property(e => e.Id).ValueGeneratedNever();
=======
            entity.HasKey(e => e.Id).HasName("PK__Wallet__3214EC07F5DD1946");

            entity.ToTable("Wallet");

>>>>>>> Stashed changes
            entity.Property(e => e.Balance).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.CreatedAt).HasColumnType("datetime");
            entity.Property(e => e.CurrencyCode).HasMaxLength(255);
            entity.Property(e => e.UpdatedAt).HasColumnType("datetime");

            entity.HasOne(d => d.User).WithMany(p => p.Wallets)
                .HasForeignKey(d => d.UserId)
<<<<<<< Updated upstream
                .HasConstraintName("FK__Wallet__UserId__4222D4EF");
=======
                .HasConstraintName("FK__Wallet__UserId__4316F928");
>>>>>>> Stashed changes
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
<<<<<<< Updated upstream
}
=======
}
>>>>>>> Stashed changes
