// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace STP.Repository.Models;

public partial class TripeTypePricing
{
    public int Id { get; set; }

    public string Name { get; set; }

    public int TripType { get; set; }

    public int MinPerson { get; set; }

    public int MaxPerson { get; set; }

    public decimal PricePerPerson { get; set; }

    public int? Status { get; set; }

    public virtual TripType TripTypeNavigation { get; set; }
}