// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace STP.Repository.Models;

public partial class Trip
{
    public int Id { get; set; }

    public int? PickUpLocationId { get; set; }

    public int? DropOffLocationId { get; set; }

    public int? ToAreaId { get; set; }

    public int? MaxPerson { get; set; }

    public int? MinPerson { get; set; }

    public decimal? UnitPrice { get; set; }

    public DateOnly? BookingDate { get; set; }

    public TimeOnly? HourInDay { get; set; }

    public int? PricingId { get; set; }

    public int? TripTypeId { get; set; }

    public int? Status { get; set; }

    public virtual ICollection<Booking> Bookings { get; set; } = new List<Booking>();

    public virtual ICollection<CarTrip> CarTrips { get; set; } = new List<CarTrip>();

    public virtual Location DropOffLocation { get; set; }

    public virtual Location PickUpLocation { get; set; }

    public virtual TripType TripType { get; set; }
}