// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace STP.Repository.Models;

public partial class TripType
{
    public int Id { get; set; }

    public int FromAreaId { get; set; }

    public int ToAreaId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public decimal BasicePrice { get; set; }

    public int? Status { get; set; }

    public virtual ICollection<TripeTypePricing> TripeTypePricings { get; set; } = new List<TripeTypePricing>();

    public virtual ICollection<Trip> Trips { get; set; } = new List<Trip>();
}